### ISSUE TITLE
New apps are missing GCM_SENDER_ID in build.yaml

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/plugin-rogerthat-control-center#170]
This causes errors on the Android client.

- Get it from the app's backend (Google Cloud Messaging sender id) when creating a new app
- Add it to the following build.yamls
  - be-alken
  - be-anzegem
  - be-diksmuide
  - be-hove
  - be-lovendegem
  - be-moorslede
  - be-nieuwerkerken
  - be-staden

**Comment by lucasvanhalst** [comment]
According to this https://console.cloud.google.com/debug?repo=appengine:%3Fservice%3Ddefault%26version%3D20170626t091250&fp=%2Fplugins%2Frogerthat_control_center%2Fbizz%2Fbackends.py&dlv=4&project=gig-mobile-cc&organizationId=295158850937&app=GAE:default@20170626t091250&bp=553b4efb6f33f-9293-6b21c (see on github https://github.com/rogerthat-platform/plugin-rogerthat-control-center/blob/13450db8ea2b1992e929b8654c4a67edd69c81d6/plugins/rogerthat_control_center/bizz/backends.py#L62) it should not occur anymore, has been fixed since 20/06.

be-halen, be-verune, be-nieuwerkerken and be-bree were created _after_ 20/06 however, so can you still validate if it really is the case

**Comment by bart-at-mobicage** [comment]
I'ts only missing in the build.yaml files that I listed above, so it seems it's fixed for newer apps like halen, veurne...

**Comment by lucasvanhalst** [comment]
http://gitlab.mobicage.com/rogerthat/apps/merge_requests/27/diffs
