### ISSUE TITLE
Image upload simplifications, part 2

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/plugin-rogerthat-control-center#228]
I want to simplify uploading images. I want that people only have to upload the iOS splash screen (transparant, 1024x1024)

- [x] I would display the iOS splash screen image first
- [x] I would add checkboxes to the iOS/Android/homescreen-logo/registration-logo/about-header images (checked by default for new apps). Show previews though. When a new splash screen image is uploaded, regenerate the images if needed.
- iOS icon, Android icon and Homescreen header
  - [x] Auto-generate from iOS splash screen
- Registration logo and about header:
  - [x] Use homescreen header

This way we can just upload a new transparent iOS icon and the Splash/Android/Facebook/Homescreen/Registration/About images are auto-generated.

**Comment by abom** [comment]
The splash screen image is generated from a transparent image itself and we only store static data about every image (image size...etc). So i think we also need to store the transparent image.

Do you need the CC to remember/store if the auto-generation is checked or not for every image, only the state of this check boxes will need to be stored in e.g. DB?

@lucasvanhalst What do you think of using a DB model to store images information?

**Comment by lucasvanhalst** [comment]
@bart-at-mobicage 
> iOS icon, Android icon and Homescreen header -> Auto-generate from iOS splash screen
Shouldn't this be the other way around?

**Comment by lucasvanhalst** [comment]
Let's make it simpler: keep the current uploading/deteting of images, but do not generate anything (so no checkboxes on the `edit image` pages)

- [ ] Add a FAB in the bottom right of the images overview page which they can click, there they can upload an image which will be used to generate everything else.
- [ ] On this page, there are checkboxes (generate app icon, generate homescreen item, etc) which are all checked by default. So when uploading an image on that page, those images will be generated. This is the only page they can use to automatically generate images.
- [ ] I guess it would be nice to have a preview of the selected generated images on this page, since you already made a handler for this I think it's won't be too much work

**Comment by abom** [comment]
I think we cannot have a preview of something that's not uploaded yet, image generation is done on the server side, and don't know for sure if we can do it on client side too.

**Comment by lucasvanhalst** [comment]
Right, nevermind that then
